In [1]:
import numpy as np # kütüphanein import edilmesi

### Numpy Array

In [5]:
benimListem = [20,30,40] # pyhton klasik liste oluşturulması

In [6]:
benimListem

[20, 30, 40]

In [7]:
type(benimListem) # türün görüntülenmesi

list

In [9]:
np.array(benimListem) # listeyi numpy kullanarak arraya dönüştürdük..

array([20, 30, 40])

In [11]:
type(np.array(benimListem)) # listeyi numpy olarak dönüştürmüştük bu sefer türünü gösterdik

numpy.ndarray

In [12]:
benimMatrixListem = [[10,20,30], [40,50,60], [70,80,90]] # halen listedir.

In [13]:
benimMatrixListem

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [15]:
type(benimMatrixListem) # türü halen liste türünde

list

In [17]:
benimMatrixListem[0][2] # bu şekilde halen liste türünde olduğunu anlayabiliriz...

30

In [19]:
np.array(benimMatrixListem) # numpy kullanarak bunu matrix türüne dönüştürdük.

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [22]:
type(np.array(benimMatrixListem)) # numpy türünde bir matrise dönüştürüldü...

numpy.ndarray

### Numpy Methods

#### arange methodu

In [32]:
list(range(0,10)) # pyhtonun klasik 0-10'a kadar sayıları içeren liste oluşturulmasıdır.

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
np.arange(0,10) # 0-10'a kadar sayıları içeren numpy dizini oluşturdu... 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(0,20,2) # sondaki 2 sayısı step-size'ı verir kaç atlayarak yazdıracağını belirtir. burada 2'nin katlarını atlayarak yazdırdı...

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
np.arange(0,90,3) # 0'dan başladı 90'a kadar üçer üçer atlayarak numpy arrayine ekle

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87])

#### zeros 

In [43]:
np.zeros(5) # elemanları sıfır olan içerisinde 5 tane eleman bulunan bir numpy array oluşturur...

array([0., 0., 0., 0., 0.])

In [44]:
np.zeros((9,9)) # 9x9'luk elemanları sıfır olan bir matris oluşturdu...

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
np.ones(5) # elemanları bir olan içerisinde 5 tane eleman bulunan bir numpy array oluşturur...

array([1., 1., 1., 1., 1.])

In [47]:
np.ones((9,9)) # 9x9'luk elemanları bir olan bir matris oluşturdu...

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### linspace

> linspace bir sayı aralığında eşit aralıklarla istenilen adet kadar numpy arrayi döndürür

In [53]:
np.linspace(0,20,6) #0-20 arasında 6 adet sayı alacak ama bu sayılar arasında eşit mesafe vardır

array([ 0.,  4.,  8., 12., 16., 20.])

> mesela yukarıdaki dizinde 0-20 arasında ama elemanlar arasında mesafe aynıdır. Örneğin 0-4 elemanları arasındaki fark ile 4-8 arasındaki fark aynıdır ve bu işlem en son değere kadar devam eder.

In [54]:
np.linspace(0,20,10) #0 ile 10 arasında 10 tane elemanı arraye atar ama bu elemanlar arasındaki fark eşittir...

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

#### eye 

> bu method ise bizlere identity matris yani birim matrisler oluşturmamıza olanak sağlar...

In [56]:
np.eye(10) #10x10'luk bir birim matrisi oluşturdu.

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [58]:
np.eye(3) # 3x3'lük bir birim matrisi oluşturdu...

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### random

> numpy'da bulunan random kütüphanesi klasik pyhtonda bulunan random kütüphanesiden biraz farklıdır. Bu farklılık numpy random kütüphanesi normal dağılıma sahip rastgele sayılar üretir...

In [61]:
np.random.randn(4) # 4 tane normal dağılıma sahip sayılar üretir....

array([ 0.10767333, -0.39555576,  0.63751574, -0.24075784])

In [65]:
np.random.rand(4) # bu da normal dağılıma sahip pozitif sayılar ürettirir.

array([0.85279348, 0.29469934, 0.23943255, 0.03371128])

In [68]:
np.random.randn(4,4) # normal dağılıma sahip 4x4'lük bir matris ürettirdik...

array([[-2.40772662,  1.27253883, -0.33953504,  0.68849824],
       [-1.83611354,  1.34616434,  1.39633438, -0.99943632],
       [ 0.11945559,  1.67923244,  0.36561331,  2.00246828],
       [-0.87318704,  0.14634593, -0.69587183, -0.87770961]])

In [70]:
np.random.rand(4,4) # normal dağılıma sahip 4x4'lük bir pozitif sayılardan oluşan bir matris ürettirdi...

array([[0.60754394, 0.31041441, 0.06769213, 0.11669729],
       [0.35741859, 0.79357646, 0.85846953, 0.58593028],
       [0.59941206, 0.58989468, 0.8129964 , 0.93950074],
       [0.88519957, 0.60840062, 0.20607751, 0.63149393]])

In [72]:
np.random.randint(1,10) # 1-10 arasında rastgele bir tane sayı üretti ama burada önemli olan nokta şurasıdır. 1 sayısını üretebilir ama 
# 10 stop value olduğu için ne kadar çalıştırırsan çalıştır 10'u üretmez....

7

In [74]:
np.random.randint(1,300,5) #1-300'e kadar rastgele 5 tane sayı üretir

array([194,  56, 237, 250,  22])

In [76]:
dizi_01 = np.arange(0,30) # 0-30'a kadar olan sayıların (30 stop value olduğu için dahil değil) dizi_01 değişkenine atadı...

In [78]:
dizi_01 # dizi_01 içerisinde artık bu tanımlıdır....

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [86]:
dizi_02_random = np.random.randint(0,100,20) #0-100 arasında 30 tane değeri dizi_02_random değişkenine atadık...

In [87]:
dizi_02_random #dizi_02_random içerisinde artık bu dizi tanımlıdır

array([55, 77, 29, 62, 98, 55, 78, 23,  5, 84, 87, 63, 85,  9, 15,  0, 91,
        5, 71, 71])

### Numpy Array Methods

> reshape tanımlı olan diziyi matrise çevirir ama bazı şartları vardır bu şart ise çevrilecek olan dizinin istenilen matris özelliklerine uyması gerekliliğidir.

Örneğin;
* 30 tane elemanı olan bir diziyi 5x5 matrise bölünemez çünkü 5x5 olan bir matris 25 adet veri tutabilir.
* Başka bir örnek vermek gerekirse 20 tane veri olan bir matrisi 4x4 olan bir matrise bölemezsin çünkü 4x4 olan bir matris en fazla (4x4=16) şeklinde en fazla 16 adet veri tutar.

aşağıdaki örneğe bakacak olursak dizi_01 arrayinde 30 adet veri vardır buna uygun olarak 6x5 şeklinde matris bölünlenmesi yapılabilir çünkü (6x5=30) olduğundan 6x5 matrisi 30 adet veriye ihtiyaç duyar. bunu diğer türlü yani 5x6 olarak da bölebildiğimiz anlamına gelir.
aynı şekilde aşağıdaki dizi_01 matrisini 5x5 matrisine bölemezsin çünkü (5x5=25) olan bir matris 25 adet veriye ihtiyaç duyar ama bizim dizimizde 30 adet veri vardır.

Bu şartlar sağlanmadığında aşağıdaki reshape methodu hata verir...

In [91]:
dizi_01.reshape(6,5) # 6x5 matrisi 30 adet veriye ihtiyaç duyar ve dataframe'de 30 adet veri vardır yani fonksiyon çalışır.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [92]:
dizi_01.max() # dizi_01 arrayi içerisindeki en büyük sayısal değeri verir

29

In [93]:
dizi_02_random.max() # dizi_02_random arrayi içerisindeki en büyük sayısal değeri verir

98

In [94]:
dizi_01.min() # dizi_01 arrayi içerisindeli en küçük sayısal değeri verir

0

In [97]:
dizi_02_random.min() # dizi_02_random arrayi içerisindeki minimum değeri verir

0

In [104]:
dizi_02_random.argmax() # dizi içerisindeki en yüksek değer kaçıncı sıradadır ?

4

In [105]:
dizi_02_random.argmin() # dizi içerisindeki en küçük değer kaçıncı sıradadır

15

In [99]:
dizi_02_random.std() # standard sapmayı verir

32.34234839958286

In [100]:
dizi_02_random.mean() # ortalamayı verir

53.15

In [102]:
dizi_02_random.sum() # dizi içerisindeki bütün değerleri toplar

1063

In [108]:
reshape_dizi = dizi_01.reshape(6,5) # reshape yapılmış diziyi bir değişkene atadık

In [109]:
reshape_dizi # yazdırdım

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [114]:
reshape_dizi.shape # matrisin boyutlarını verir yani 6 sütun 5 satırdan oluştuğunu söyler ve ayrıca shape'de parantez yoktur 
#çünkü bir fonksiyon veya method değildir.

(6, 5)