### Numpy indexle veri değiştirme işlemleri

In [1]:
import numpy as np

In [3]:
benimDizim = np.arange(0,15)

In [4]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
benimDizim[5] # 5. indexteki ifadeyi getir

5

In [6]:
benimDizim[3:8] # starting index: 3 , stop index: 8 yani üçüncü ile sekizinci index arasını bana getir --> slacing

array([3, 4, 5, 6, 7])

Örneğin:
> üçüncü ile sekizinci index arasındaki sayıları değiştirmek isteyelim bunu yine arrayin bir özelliği olan slacing ile yapabiliriz...

In [9]:
benimDizim[3:8] = -5 # üçüncü index ile sekizinci index arasındaki sayıları -5 olarak değiştir...

In [10]:
benimDizim # arayi bize gösterir

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [13]:
baskaDizi = np.arange(0,24) # başka bir dizi oluşturalım...

In [14]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
slacingDizi = baskaDizi[4:9]

In [23]:
slacingDizi 

array([4, 5, 6, 7, 8])

In [24]:
type(slacingDizi)

numpy.ndarray

> dizi içerisindeki değerleri nasıl değiştirebiliriz...

In [25]:
# slacingDizi = 700 # değişkenin türünü değiştirir yani numpy.array olan tür int'e dönüşür...

In [26]:
# type(slacingDizi) # int türünde olduğunu gösterir

In [27]:
slacingDizi[:] = 700 # aralıktaki sayıları 700' eşitle 

In [28]:
slacingDizi

array([700, 700, 700, 700, 700])

In [30]:
baskaDizi # başka değişkende olan aralıktaki sayıları da 700 yapar 

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

> ana dizinin içerisinden bir dizi parça seçilir (slicing). bu parçanın içerisinde değişiklik yaparsan eğer bu diğer ana dizinin etkilenir...

* Peki bu ana dizi içerisinde orijinalini bozmadan değişiklik yapılabilir mi ? 
-> Evet yapılabilir. Bunun için ana diziyi kopyalaman ve onun üzerinden değişiklik yapman gerekir...

In [55]:
ornekDizi = np.arange(0,24) # yeni bir dizi oluşturduk

In [56]:
ornekDizi # görmek istedik

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [48]:
ornekDiziKopyasi = ornekDizi.copy() #ornekDiziyi yeni oluşturulan değişkene kopyaladık...

In [57]:
ornekDiziKopyasi # ve kopyalanan değişikliği gördük

array([  0,   1,   2, 800, 800, 800, 800, 800, 800,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [58]:
OrnekDiziKopyaSlicing = ornekDiziKopyasi[3:9] # slicing gerçekleştirildi ve yeni değişkene atadık

In [59]:
OrnekDiziKopyaSlicing

array([800, 800, 800, 800, 800, 800])

In [60]:
OrnekDiziKopyaSlicing[:] = 800

In [61]:
OrnekDiziKopyaSlicing

array([800, 800, 800, 800, 800, 800])

In [66]:
ornekDizi # asıl olan veriyi değiştirmedi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [67]:
ornekDiziKopyasi # kopyasını değiştirdi

array([  0,   1,   2, 800, 800, 800, 800, 800, 800,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

#### matrislerle işlemler

In [68]:
benimListem = [[10,20,30],[20,30,40],[50,60,70]]

In [70]:
benimMatrisDizim = np.array(benimListem) # diziyi matrise çevirdik

In [71]:
benimMatrisDizim

array([[10, 20, 30],
       [20, 30, 40],
       [50, 60, 70]])

In [72]:
benimMatrisDizim[0] # 0. indexteki satırı verecektir

array([10, 20, 30])

In [80]:
benimMatrisDizim[1][2] # 1. index satırından 2. indexe sahip olan sütundaki değeri getirir yani 60'ı getirecektir

40

In [81]:
benimMatrisDizim[1,2] # yukarıdaki yazımla burası arasında fark yoktur --> row: 1 , column: 2

40

In [83]:
benimMatrisDizim[1:,2] # starting index olan birinci satırı es geç ikinci ve üçüncü satırları seçer sütunların da 2. indexini seç...

array([40, 70])

In [85]:
benimMatrisDizim[2:,1:] # starting index olan 2. satırı es geçti yine aynı şekilde 1. index olan column'ı da es geçti 60,70'i yazdırdı

array([[60, 70]])

In [86]:
yeniListe = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]

In [87]:
yeniMatris = np.array(yeniListe)

In [88]:
yeniMatris

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [90]:
yeniMatris[[4,2,0]] # 4. satırdaki değer, 2. satırdaki değer, 0. satırdaki değer --> bunların her birini seçti

array([[21, 22, 23, 24, 25],
       [11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5]])

In [92]:
type(yeniMatris[[4,2,0]]) # array türünde olmaya devam edecektir.

numpy.ndarray

#### operasyonlar

In [95]:
yeniBirDizi = np.random.randint(0,100,20) #0'dan 100'e kadar rastgele 20 adet sayı üret ve arraya aktar

In [96]:
yeniBirDizi

array([ 3, 74, 19, 11, 36, 47,  0, 38, 62, 61, 37, 72, 22, 23, 97, 49, 86,
       13, 20, 16])

In [97]:
yeniBirDizi > 24 # dizi içerisinde 24'ten büyük değerleri true veya false olarak döndürecektir...

array([False,  True, False, False,  True,  True, False,  True,  True,
        True,  True,  True, False, False,  True,  True,  True, False,
       False, False])

In [100]:
sonucDizisi = yeniBirDizi > 24 # dizi içerisindeki 24'ten büyük değerleri true veya false olarak döndürür ve değişkene atar

In [101]:
sonucDizisi # değişkeni görüntüledik

array([False,  True, False, False,  True,  True, False,  True,  True,
        True,  True,  True, False, False,  True,  True,  True, False,
       False, False])

In [102]:
yeniBirDizi

array([ 3, 74, 19, 11, 36, 47,  0, 38, 62, 61, 37, 72, 22, 23, 97, 49, 86,
       13, 20, 16])

In [104]:
yeniBirDizi[sonucDizisi] # 24'ten büyük sayıları bize filtreliyor yani true false döndürmek yerine direkt sayıları yazıyor

array([74, 36, 47, 38, 62, 61, 37, 72, 97, 49, 86])

In [105]:
yeniBirDizi # dizinin içerisinde bir değişiklik söz konusu değil...

array([ 3, 74, 19, 11, 36, 47,  0, 38, 62, 61, 37, 72, 22, 23, 97, 49, 86,
       13, 20, 16])

> sonuc dizisine ihtiyaç duymadan da değiştirebilirsin

In [107]:
yeniBirDizi[yeniBirDizi > 24] # bunu herhangi bir değişkene atamadan da 24'ten büyük sayıları filtreleyebilirsin

array([74, 36, 47, 38, 62, 61, 37, 72, 97, 49, 86])

In [108]:
sonDizi = np.arange(0,24)

In [109]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [110]:
sonDizi + sonDizi # iki aynı diziyi topladım...

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [111]:
sonDizi - sonDizi # iki aynı diziyi çıkartırım sıfır dizisini verecektir.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [113]:
sonDizi * sonDizi # iki aynı diziyi çarpıyor yani bir nevi karesini alma

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [115]:
# sonDizi / sonDizi # iki aynı diziyi bölme işlemi ---> içi tamamen 1 sayılarıyla oluşan bir dizi oluşturur 0 hariç çünkü 0/0 tanımsızdır.

In [117]:
np.sqrt(sonDizi) # son dizinin karekökünü alır...

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [119]:
np.sum(sonDizi) #içerisindeki değerlerin tamamını toplar

276

In [121]:
np.median(sonDizi) # dizinin medianını bulur

11.5

In [123]:
np.mean(sonDizi) # dizinin ortalamasını verir.

11.5

In [127]:
np.max(sonDizi) # max değerini verir

23

In [128]:
np.min(sonDizi) # min değerini verir.

0

In [130]:
np.std(sonDizi) # dizinin standart sapmasını verir

6.922186552431729